export const dir = {
	src: {
		root: "src/",
		stylesheets: "src/assets/sass/",
		javascripts: "src/assets/js/",
		images: "src/assets/images/",
		fonts: "src/assets/fonts/",
		icon: "src/assets/icons/",
		html: "src/assets/html/pages/",
		pdf: "src/assets/html/pdf/",
		video: "src/assets/html/video/",
		public: "src/public/",
	},
	build: {
		root: "dist/",
		stylesheets: "dist/assets/css/",
		javascripts: "dist/assets/js/",
		images: "dist/assets/images/",
		fonts: "dist/assets/fonts/",
		svg: "dist/assets/svg/",
		html: "dist/",
		pdf: "dist/assets/html/pdf/",
		video: "dist/assets/html/video/",
		public: "dist/",
	},
	njk: {
		root: "src/assets/html",
		json: "../../src/assets/html/_config/site.json",
		srcExtention: ".njk",
		buildExtention: ".html",
	},
};
